applicationApiVersion: v1beta1

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  falco.serviceAccount.name:
    title: Falco Service Account
    description: Service account to assign to Falco DaemonSet
    type: string
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
        - type: ClusterRole
          rulesType: PREDEFINED
          rulesFromRoleName: cluster-admin
  image:
    type: string
    default: $REGISTRY/falco:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: falco.image.registry
            repo: falco.image.repository
            tag: falco.image.tag
  falco.ebpf.enabled:
    title: Enable eBPF support for Falco
    description: |-
      Mark this checkbox if you are using a Kernel newer than 4.14. The default
      value for newly created clusters is enabled, but if you are using an older
      kernel, please uncheck this checkbox and use the Sysdig Kernel module for
      capturing the system calls.
    type: boolean
    default: true
required:
- name
- namespace
- image
